# -*- coding: utf-8 -*-
"""epuck_controller

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zysgxQti0tIF-_ssG74RQMmKYC2rXZ4D
"""

from controller import Robot
import math

robot = Robot()
TIME_STEP = 32
trans_field = robot.getSelf().getField("translation")
angle = 0.0
radius = 1.0
center = [0, 0.05, 0]

while robot.step(TIME_STEP) != -1:
    angle += 0.02
    x = center[0] + radius * math.cos(angle)
    z = center[2] + radius * math.sin(angle)
    trans_field.setSFVec3f([x, 0.05, z])